vich_uploader:
    db_driver: orm

    mappings:
        medias_images:
            uri_prefix: /uploads/medias/images
            upload_destination: '%kernel.project_dir%/public/uploads/medias/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true

        categories_images:
            uri_prefix: /uploads/categories/images
            upload_destination: '%kernel.project_dir%/public/uploads/categories/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true

        categories_icon_images:
            uri_prefix: /uploads/categories/iconeimages
            upload_destination: '%kernel.project_dir%/public/uploads/categories/iconeimages'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true

        users_avatars:
            uri_prefix: /uploads/users/avatars
            upload_destination: '%kernel.project_dir%/public/uploads/users/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true

        users_couvertures:
            uri_prefix: /uploads/users/couvertures
            upload_destination: '%kernel.project_dir%/public/uploads/users/couvertures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true

        offres_images:
            uri_prefix: /uploads/offres/images
            upload_destination: '%kernel.project_dir%/public/uploads/offres/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true

        rapports_files:
            uri_prefix: /uploads/rapports/fichiers
            upload_destination: '%kernel.project_dir%/public/uploads/rapports/fichiers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true

        messages_files:
            uri_prefix: /uploads/rapports/fichiers
            upload_destination: '%kernel.project_dir%/public/uploads/rapports/fichiers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true